kreyu_data_table:
  defaults:
    themes:
      - "@KreyuDataTable/themes/bootstrap_5.html.twig"
      - "data_table/theme.html.twig"
    pagination:
      persistence_enabled: true
      per_page_choices: [5, 10, 20]
