framework:
  messenger:
    transports:
      async:
        dsn: "doctrine://default?auto_setup=0"
        retry_strategy:
          max_retries: 3
          delay: 5000
          multiplier: 2
          max_delay: 0
      sync: "sync://"
      failed: "doctrine://default?queue_name=failed"
    routing:
      'App\Application\Shared\Bus\AsyncMessageInterface': async

    default_bus: command.bus
    buses:
      command.bus:
        default_middleware: false
        middleware:
          - handle_message
          - doctrine_transaction
      query.bus:
        default_middleware: false
        middleware:
          - handle_message
      async.message.bus: ~
