framework:
  messenger:
    failure_transport: failed
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - validation
          - doctrine_transaction
      query.bus:
        middleware:
          - validation
      event.bus:
        middleware:
          - validation
    transports:
      async:
        dsn: "doctrine://default?auto_setup=0"
        retry_strategy:
          max_retries: 3
          delay: 5000
          multiplier: 2
          max_delay: 0
      sync: "sync://"
      failed: "doctrine://default?queue_name=failed"
    routing:
      'App\Application\Message\Command\*': sync
