framework:
  messenger:
    failure_transport: failed
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - dispatch_after_current_bus
          - doctrine_transaction
      message.bus: ~
      event.bus: ~
    transports:
      async:
        dsn: "doctrine://default?auto_setup=0"
        retry_strategy:
          max_retries: 3
          delay: 5000
          multiplier: 2
          max_delay: 0
      sync: "sync://"
      failed: "doctrine://default?queue_name=failed"
    routing:
      'App\Domain\Event\*': async
