twig:
  file_name_pattern: "*.twig"
  form_themes:
    - "bootstrap_5_layout.html.twig"
    - "form/theme.html.twig"
  globals:
    locales: "%app.allowed_locales%"

when@test:
  twig:
    strict_variables: true
