vich_uploader:
  db_driver: orm

  mappings:
    videos:
      upload_destination: "%app.videos.path%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    testResults:
      upload_destination: "%app.testResults.path%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
