controllers:
  resource:
    path: ../src/Infrastructure/Controller/
    namespace: App\Infrastructure\Controller
  prefix: /{_locale}
  requirements:
    _locale: "%app.allowed_locales%"
  type: attribute

home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_module_index
