controllers:
  resource:
    path: ../src/Presentation/Controller/
    namespace: App\Presentation\Controller
  prefix: /{_locale}
  requirements:
    _locale: "%app.allowed_locales%"
  type: attribute

home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_module_index
