parameters:
  app.default_locale: en
  app.fallback_locale: en
  app.allowed_locales: en|pl
  app.test_category: introductory|periodic
  app.admin_email: "%env(ADMIN_EMAIL)%"
  app.admin_password: "%env(ADMIN_PASSWORD)%"
  app.encryption.key: "%env(ENCRYPTION_KEY)%"

  app.logs.path: "/var/log/test-manager.log"
  app.base.path: "/home/uploads"
  app.videos.path: "%app.base.path%/videos"
  app.testResults.path: "%app.base.path%/testResults"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    App\Application\Shared\Bus\CommandBusHandlerInterface:
      public: true
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    App\Application\Shared\Bus\QueryBusHandlerInterface:
      public: true
      tags:
        - { name: messenger.message_handler, bus: query.bus }

    App\Application\Shared\Bus\AsyncMessageBusHandlerInterface:
      public: true
      tags:
        - { name: messenger.message_handler, bus: async.message.bus }

  App\Infrastructure\Shared\Logger:
    public: true

  app.logger:
    alias: 'App\Infrastructure\Shared\Logger'

  Psr\Log\LoggerInterface: "@app.logger"

  App\:
    resource: "../src/"

  App\Infrastructure\Bus\CommandBus:
    arguments:
      - "@command.bus"

  App\Infrastructure\Bus\QueryBus:
    arguments:
      - "@query.bus"

  App\Infrastructure\Bus\AsyncMessageBus:
    arguments:
      - "@async.message.bus"
