parameters:
  app.default_locale: en
  app.fallback_locale: en
  app.allowed_locales: en|pl
  app.test_category: introductory|periodic
  app.admin_email: "%env(ADMIN_EMAIL)%"
  app.admin_password: "%env(ADMIN_PASSWORD)%"
  app.encryption.key: "%env(ENCRYPTION_KEY)%"

  app.base.path: "/home/uploads"
  app.videos.path: "%app.base.path%/videos"
  app.testResults.path: "%app.base.path%/testResults"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: "../src/"
